stages:
  clean_transactions:
    cmd: python -m aml_detection.dataset_loader
    deps:
      - aml_detection/dataset_loader.py
      - data/raw/HI-Small_Trans.csv
    outs:
      - data/interim/transaction/transaction_cleaned.parquet

  merge_accounts:
    cmd: python -m aml_detection.dataset_loader_accounts
    deps:
      - aml_detection/dataset_loader_accounts.py
      - data/interim/transaction/transaction_cleaned.parquet
      - data/raw/HI-Small_accounts.csv
    outs:
      - data/interim/merged/transactions_merged.parquet
  build_features:
    cmd: python -m aml_detection.features
    deps:
      - aml_detection/features.py
      - data/interim/merged/transactions_merged.parquet
    outs:
      - data/processed/transactions_features.parquet